services:
  dumbbudget:
    image: dumbwareio/dumbbudget:latest
    container_name: dumbbudget
    ports:
      - ${DUMB_PORT:-3000}:3000
    volumes:
      - ${DUMBBUDGET_DATA_PATH:-/opt/dumbsuite/dumbbudget}:/app/data
    environment:
      - DUMBBUDGET_PIN=${DUMB_PIN:-}

  dumbdo:
    image: dumbwareio/dumbdo:latest
    ports:
      - ${DUMB_PORT:-3000}:3000
    volumes:
      - ${DUMBDO_DATA_PATH:-/opt/dumbsuite/dumbdo}:/app/data
    environment:
      - DUMBDO_PIN=${DUMB_PIN:-}

  dumbdrop:
    image: dumbwareio/dumbdrop:latest
    ports:
      - ${DUMB_PORT:-3000}:3000
    volumes:
      - ${DUMBDROP_DATA_PATH:-/opt/dumbsuite/dumbdrop}:/app/data
    environment:
      - DUMBDROP_PIN=${DUMB_PIN:-}

  dumbpad:
    image: dumbwareio/dumbpad:latest
    ports:
      - ${DUMB_PORT:-3000}:3000
    volumes:
      - ${DUMBPAD_DATA_PATH:-/opt/dumbsuite/dumbpad}:/app/data
    environment:
      - DUMBPAD_PIN=${DUMB_PIN:-}

  dumbkan:
    image: dumbwareio/dumbkan:latest
    ports:
      - ${DUMB_PORT:-3000}:3000
    volumes:
      - ${DUMBKAN_DATA_PATH:-/opt/dumbsuite/dumbkan}:/app/data
    environment:
      - DUMBKAN_PIN=${DUMB_PIN:-}
