services:
  dumbbudget:
    image: dumbwareio/dumbbudget:latest
    container_name: dumbbudget
    restart: unless-stopped
    networks:
      - dumb-net
    ports:
      - ${DUMBBUDGET_PORT:-3333}:3000
    volumes:
      - ${DUMBBUDGET_DATA_PATH:-/opt/dumbsuite/dumbbudget}:/app/data
    environment:
      - DUMBBUDGET_PIN=${DUMB_PIN:-}

  dumbdo:
    image: dumbwareio/dumbdo:latest
    container_name: dumbdo
    restart: unless-stopped
    networks:
      - dumb-net
    ports:
      - ${DUMBDO_PORT:-3334}:3000
    volumes:
      - ${DUMBDO_DATA_PATH:-/opt/dumbsuite/dumbdo}:/app/data
    environment:
      - DUMBDO_PIN=${DUMB_PIN:-}

  dumbdrop:
    image: dumbwareio/dumbdrop:latest
    container_name: dumbdrop
    restart: unless-stopped
    networks:
      - dumb-net
    ports:
      - ${DUMBDROP_PORT:-3335}:3000
    volumes:
      - ${DUMBDROP_DATA_PATH:-/opt/dumbsuite/dumbdrop}:/app/data
    environment:
      - DUMBDROP_PIN=${DUMB_PIN:-}

  dumbpad:
    image: dumbwareio/dumbpad:latest
    container_name: dumbpad
    restart: unless-stopped
    networks:
      - dumb-net
    ports:
      - ${DUMBPAD_PORT:-3336}:3000
    volumes:
      - ${DUMBPAD_DATA_PATH:-/opt/dumbsuite/dumbpad}:/app/data
    environment:
      - DUMBPAD_PIN=${DUMB_PIN:-}

  dumbkan:
    image: dumbwareio/dumbkan:latest
    container_name: dumbkan
    restart: unless-stopped
    networks:
      - dumb-net
    ports:
      - ${DUMBKAN_PORT:-3337}:3000
    volumes:
      - ${DUMBKAN_DATA_PATH:-/opt/dumbsuite/dumbkan}:/app/data
    environment:
      - DUMBKAN_PIN=${DUMB_PIN:-}

networks:
  dumb-net:
    name: dumb-net
